language: node_js
# Trying to configure npm as well? Look a little bit further down this file.
node_js:
  - "8.9.4"
sudo: false
script: npm run lint && npm test -- --coverage
notifications:
  email: false
before_script:
  - npm run build-all